[package]
name = "mruby-rust-poop"
version = "0.0.1"
authors = ["Dennis Walters <pooster@gmail.com"]

[dependencies]
mferuby = { git = "https://github.com/hone/mferuby.git", branch = "wip" }
lazy_static = "0.2.1"

[lib]
crate-type = ["staticlib"]
